version: '3.8'

services:
  blog_backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://bloguser:FQQWfbRL!SNI@68.183.192.23:3306/blog_db"
      ALGORITHM: "HS256"
      SECRET_KEY: "BADSECRET"
      ACCESS_TOKEN_EXPIRE_MINUTES: 12000

  