"""comment id auto increment

Revision ID: 16d00446c936
Revises: 8eff56c97f49
Create Date: 2026-03-23 21:33:47.790155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16d00446c936'
down_revision: Union[str, Sequence[str], None] = '8eff56c97f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_comments', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=300000),
               existing_nullable=False)
    op.alter_column('posts', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=300000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('post_comments', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
