"""comment id auto increment

Revision ID: 20b0000d7923
Revises: 16d00446c936
Create Date: 2026-03-23 21:35:28.665426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20b0000d7923'
down_revision: Union[str, Sequence[str], None] = '16d00446c936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'post_comments',
        'id',
        existing_type=sa.Integer(),
        nullable=False,
        autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('post_comments', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
