"""add follows table

Revision ID: 34241c7e8124
Revises: 3a6097a258c4
Create Date: 2026-02-05 20:57:01.725802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34241c7e8124'
down_revision: Union[str, Sequence[str], None] = '3a6097a258c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RECOVER_YOUR_DATA_info')
    op.create_unique_constraint('uq_follows', 'followers', ['follower_id', 'followed_id'])
    op.alter_column('posts', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=300000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_follows', 'followers', type_='unique')
    op.create_table('RECOVER_YOUR_DATA_info',
    sa.Column('READ_ME', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
