"""post votes

Revision ID: 6fd80a56019b
Revises: 6828a0bbb324
Create Date: 2026-03-06 20:07:42.944070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fd80a56019b'
down_revision: Union[str, Sequence[str], None] = '6828a0bbb324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=300000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
