"""normalize post and user

Revision ID: 9b4b5cf51ffe
Revises: a963897b6823
Create Date: 2026-07-11 13:58:07.373914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b4b5cf51ffe'
down_revision: Union[str, Sequence[str], None] = 'a963897b6823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.alter_column('posts', 'user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('posts', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('users', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.String(length=10000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('posts', 'user_avatar',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('FK_e6d38899c31997c45d128a8973b')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
