"""normalize post and comment models

Revision ID: a963897b6823
Revises: 20b0000d7923
Create Date: 2026-07-03 23:57:09.265805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a963897b6823'
down_revision: Union[str, Sequence[str], None] = '20b0000d7923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IDX_78a916df40e02a9deb1c4b75ed'), table_name='user')
    op.drop_index(op.f('IDX_e12875dfb3b1d92d7d7c5377e2'), table_name='user')
    op.drop_table('user')
    op.alter_column('post_comments', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.drop_column('post_comments', 'username')
    op.drop_column('post_comments', 'user_avatar')
    op.alter_column('posts', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=300000),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('users', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.String(length=10000),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.Text(length=300000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.add_column('post_comments', sa.Column('user_avatar', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('post_comments', sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.alter_column('post_comments', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('avatar_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('IDX_e12875dfb3b1d92d7d7c5377e2'), 'user', ['email'], unique=True)
    op.create_index(op.f('IDX_78a916df40e02a9deb1c4b75ed'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###
